services:
  api1:
    build: .
    hostname: api1
    command: sh -c "uv run alembic upgrade head && uv run uvicorn --host 0.0.0.0 --port 8000 app.main:app"
    expose:
      - 8000
    env_file:
      - .env.production
    depends_on:
      db:
        condition: service_healthy

  api2:
    build: .
    hostname: api2
    command: sh -c "uv run uvicorn --host 0.0.0.0 --port 8000 app.main:app"
    expose:
      - 8000
    env_file:
      - .env.production
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    hostname: db
    env_file:
      - .env.production
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U danilo -d instagram_clone"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "80:80"

volumes:
  pg_data:

