"""fix: deleted follower and following collums from USER for stopping recurion

Revision ID: 1618d342fd45
Revises: 24b75fab6a2f
Create Date: 2025-07-25 16:08:37.082266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1618d342fd45'
down_revision: Union[str, Sequence[str], None] = '24b75fab6a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
