"""fix: deleted follower and following collums for stopping recurion

Revision ID: 24b75fab6a2f
Revises: d5c411d47606
Create Date: 2025-07-25 16:05:07.485910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b75fab6a2f'
down_revision: Union[str, Sequence[str], None] = 'd5c411d47606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
