"""fix: added id column to Follow

Revision ID: 93ce67b23120
Revises: 1618d342fd45
Create Date: 2025-07-25 16:16:29.297501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ce67b23120'
down_revision: Union[str, Sequence[str], None] = '1618d342fd45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follows', 'id')
    # ### end Alembic commands ###
